### ISSUE TITLE
Create a m-i branch and Alt-Acme-Math-XS-ModuleInstall

### ISSUE THREAD

**Issue by ingydotnet** [ingydotnet/acme-math-xs-pm#3]

**Comment by ingydotnet** [comment]
We'll need a Module::Install::InlineModule module.

**Comment by karenetheridge** [comment]
On Sun, Nov 16, 2014 at 10:12:51PM -0800, Ingy döt Net wrote:

> We'll need a Module::Install::InlineModule module.

MI is not under active maintenance and people are switching off of it in
droves, so IMO this should be low priority :)

**Comment by ingydotnet** [comment]
This really only leaves DZ and EUMM. I'm not entirely comfortable with this as I don't think either is a great solution. But I see your point.

MI is easy for me to do. Much more so than MB (I haven't used MB almost at all). I'll just put MI out there and let people choose to not use it.

**Comment by karenetheridge** [comment]
On Mon, Nov 17, 2014 at 10:35:02AM -0800, Ingy döt Net wrote:

> This really only leaves DZ and EUMM. I'm not entirely comfortable with this as I don't think either is a great solution. But I see your point.
> MI is easy for me to do. Much more so than MB (I haven't used MB almost at all). I'll just put MI out there and let people choose to not use it.

Ok, if it's easy go fer it :D
